services:
  - type: web
    name: pengcity-game
    env: node
    buildCommand: npm install
    startCommand: node start.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /debug 